### PR TITLE
Update Cake.Core to 0.26.0 for net46

### PR DESCRIPTION
**Pull request by ChrisMaddock**
The current release causes verification errors when used with the latest version of Cake. Updating the version of Cake.Core should resolve that.

I've only updated the version for the net46 build - and also left the version in the test project at 0.17.0. Is that correct?

Thanks for sharing this tool! 😄

### CODE REVIEW

**Comment by DeadlyEmbrace** [comment]
This is perfect, thanks for the PR 👍

**Comment by ChrisMaddock** [comment]
Great - thanks. 😄 

Are there any planned timescales for the next release? Just asking to work out if I should package my own, or hold on for an official one. Thanks!

**Comment by DeadlyEmbrace** [comment]
I'm pushing out a release right now. Should be on the Nuget in an hour or so

**Comment by ChrisMaddock** [comment]
Brilliant - thank you!

**Pull request merged**
